config/routes.rb
Rails.application.routes.draw do

  resources :posts
  
  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    

    def index
        @new_post = Post.new
        @all_posts = Post.order(created_at: :desc).all
    end

    def create
        @new_post = Post.new(post_params)
      if @new_post.save
          redirect_to root_path
      end
    end

    def edit
        @article = Post.find(params[:id])
        # See INDEX.HTML.ERB for instructions
        # @old_comments = Post.find(params[:id])
    end

    def update
        @article = Post.find(params[:id])
        permitted_columns = params.require(:post).permit(:comment)
        @article.update_attributes(permitted_columns) #see step 18
        redirect_to root_path
    end

    def destroy
        @deleted_post = Post.find(params[:id])
        if @deleted_post.delete
            redirect_to root_path
        end
    end

    private
    def post_params
        params.require(:post).permit(:comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Practice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>

</html>

app/views/posts/edit.html.erb
<%= form_for @article do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :comment %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/index.html.erb
<div class="header">
<div class="container">
  <h1>threadly</h1>
</div>
</div>

<div class="main">
<div class="container">
  
  <!-- Form goes here -->
  <%= form_for(@new_post) do |f| %>
    <%= f.text_field :comment, :placeholder => "Share your thoughts" %>
  <%= f.submit "Post", :class => "btn" %>
  <% end %>

  <ul class="comments">
    <% @all_posts.each do |p| %>
      <li>
        <%= p.comment %>
        <br>
        <%= link_to 'Edit', edit_post_path(p), :class => 'btn-primary' %>
        <%= link_to 'Delete', p, :method => :delete, :class => 'btn-primary' %>
        <br>
        Last Updated:
        <%= p.updated_at %>
        Created: 
        <%= p.created_at %>

        <!-- each comment should populate with old comments
        CURRENT STATUS
        each comment populating with all comments for trial
        NEXT OBJECTIVE
        use CONTROLLER to store current comment into "oldcomments" before edit is made
        AFTER
        populate oldcomments under corresponding current comment -->
        
        <div>
          <ul id="oldComments">
            <% @all_posts.each do |s| %>
              <li>
                <%= s.comment %>
              </li>
            <%end%>
          </ul>
        </div>
      </li>
    <% end %>
  </ul>
  

</div>
</div>